# Pre-commit hooks for Qryon
# See https://pre-commit.com for more information
#
# Usage in .pre-commit-config.yaml:
#
#   repos:
#     - repo: https://github.com/bumahkib7/qryon
#       rev: v0.12.0  # Use the latest release
#       hooks:
#         - id: qryon
#           # Optional: customize severity threshold
#           args: ['--severity', 'warning']
#
# Or with local installation:
#
#   repos:
#     - repo: local
#       hooks:
#         - id: qryon
#           name: Qryon Security Scanner
#           entry: qryon analyze --format github
#           language: system
#           types_or: [javascript, typescript, python, rust, go, java]

- id: qryon
  name: Qryon Security Scanner
  description: Static security analyzer for polyglot projects
  entry: qryon analyze --format github
  language: system
  types_or:
    - javascript
    - jsx
    - ts
    - tsx
    - python
    - rust
    - go
    - java
  pass_filenames: true
  require_serial: false

- id: qryon-all
  name: Qryon Security Scanner (Full Scan)
  description: Run Qryon on entire repository
  entry: qryon scan . --format github
  language: system
  pass_filenames: false
  always_run: true

- id: qryon-sarif
  name: Qryon Security Scanner (SARIF)
  description: Generate SARIF output for CI/CD integration
  entry: qryon scan --format sarif --output-file qryon-results.sarif
  language: system
  pass_filenames: false
  always_run: true
