name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      options:
        - New Security Rule
        - New Language Support
        - CLI Improvement
        - Performance
        - Output/Reporting
        - Integration (CI/CD, IDE)
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: It would be great if RMA could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered
      placeholder: I also thought about...

  - type: dropdown
    id: languages
    attributes:
      label: Affected Languages (if applicable)
      multiple: true
      options:
        - JavaScript/TypeScript
        - Python
        - Rust
        - Go
        - Java
        - All Languages
        - Not Applicable

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Code examples, links to similar tools, or mockups
      placeholder: |
        ```javascript
        // Example code that should trigger the rule
        ```

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
